#get your developer keys and replce it here

CONSUMER_KEY = 'PUT YOUR DEVELOPER ACCOUNT KEYS'
CONSUMER_SECRET = 'PUT YOUR DEVELOPER ACCOUNT KEYS'
ACCESS_KEY = 'PUT YOUR DEVELOPER ACCOUNT KEYS'
ACCESS_SECRET = 'PUT YOUR DEVELOPER ACCOUNT KEYS'
